// <auto-generated />
using System;
using AbroadQs.Bot.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AbroadQs.Bot.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260203190334_AddUserPreferredLanguage")]
    partial class AddUserPreferredLanguage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AbroadQs.Bot.Data.MessageEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("DeleteNextMessages")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("EditedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("ForwardFromChatId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ForwardFromMessageId")
                        .HasColumnType("bigint");

                    b.Property<bool>("HasInlineKeyboard")
                        .HasColumnType("bit");

                    b.Property<bool>("HasReplyKeyboard")
                        .HasColumnType("bit");

                    b.Property<string>("InlineKeyboardId")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsFromBot")
                        .HasColumnType("bit");

                    b.Property<string>("MessageType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ReplyToMessageId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("ShouldDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("ShouldEdit")
                        .HasColumnType("bit");

                    b.Property<bool>("ShouldForward")
                        .HasColumnType("bit");

                    b.Property<bool>("ShouldKeepForEdit")
                        .HasColumnType("bit");

                    b.Property<long>("TelegramChatId")
                        .HasColumnType("bigint");

                    b.Property<long>("TelegramMessageId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TelegramUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Text")
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("UpdateId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ReplyToMessageId");

                    b.HasIndex("SentAt");

                    b.HasIndex("TelegramUserId");

                    b.HasIndex("TelegramChatId", "TelegramMessageId");

                    b.ToTable("Messages", (string)null);
                });

            modelBuilder.Entity("AbroadQs.Bot.Data.SettingEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Settings", (string)null);
                });

            modelBuilder.Entity("AbroadQs.Bot.Data.TelegramUserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PreferredLanguage")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<long>("TelegramUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Username")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("TelegramUserId")
                        .IsUnique();

                    b.ToTable("TelegramUsers", (string)null);
                });

            modelBuilder.Entity("AbroadQs.Bot.Data.UserMessageStateEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("DeleteNextMessages")
                        .HasColumnType("bit");

                    b.Property<string>("LastAction")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset?>("LastActionAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("LastBotMessageId")
                        .HasColumnType("int");

                    b.Property<long?>("LastBotTelegramMessageId")
                        .HasColumnType("bigint");

                    b.Property<bool>("ShouldEdit")
                        .HasColumnType("bit");

                    b.Property<bool>("ShouldKeepStatic")
                        .HasColumnType("bit");

                    b.Property<bool>("ShouldReply")
                        .HasColumnType("bit");

                    b.Property<long>("TelegramUserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("LastBotMessageId");

                    b.HasIndex("TelegramUserId")
                        .IsUnique();

                    b.ToTable("UserMessageStates", (string)null);
                });

            modelBuilder.Entity("AbroadQs.Bot.Data.MessageEntity", b =>
                {
                    b.HasOne("AbroadQs.Bot.Data.MessageEntity", "ReplyToMessage")
                        .WithMany()
                        .HasForeignKey("ReplyToMessageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AbroadQs.Bot.Data.TelegramUserEntity", "User")
                        .WithMany()
                        .HasForeignKey("TelegramUserId")
                        .HasPrincipalKey("TelegramUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ReplyToMessage");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AbroadQs.Bot.Data.UserMessageStateEntity", b =>
                {
                    b.HasOne("AbroadQs.Bot.Data.MessageEntity", "LastBotMessage")
                        .WithMany()
                        .HasForeignKey("LastBotMessageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AbroadQs.Bot.Data.TelegramUserEntity", "User")
                        .WithMany()
                        .HasForeignKey("TelegramUserId")
                        .HasPrincipalKey("TelegramUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LastBotMessage");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
